// Code generated by hertz generator.

package user

import (
	"context"

	user "github.com/ZampoRen/go-server-comon/api/model/user"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetUser .
// @router /api/user/:user_id [GET]
func GetUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.GetUserRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// TODO: 实现业务逻辑
	resp := &user.GetUserResponse{
		UserId:    req.UserId,
		Username:  "test_user",
		Email:     "test@example.com",
		CreatedAt: "2024-01-01 00:00:00",
	}

	c.JSON(consts.StatusOK, resp)
}

// CreateUser .
// @router /api/user [POST]
func CreateUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.CreateUserRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// TODO: 实现业务逻辑
	resp := &user.CreateUserResponse{
		UserId:   123,
		Username: req.Username,
		Email:    req.Email,
		Success:  true,
	}

	c.JSON(consts.StatusOK, resp)
}

// ListUsers .
// @router /api/users [GET]
func ListUsers(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.ListUsersRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 设置默认值
	if req.Page <= 0 {
		req.Page = 1
	}
	if req.PageSize <= 0 {
		req.PageSize = 10
	}

	// TODO: 实现业务逻辑
	resp := &user.ListUsersResponse{
		Users: []*user.UserInfo{
			{
				UserId:   1,
				Username: "user1",
				Email:    "user1@example.com",
			},
			{
				UserId:   2,
				Username: "user2",
				Email:    "user2@example.com",
			},
		},
		Total: 2,
		Page:  req.Page,
	}

	c.JSON(consts.StatusOK, resp)
}
